algorithm_name: 'happo' #'happo' #'heuristic2'  #'happo_continue'
experiment_name: 'continue_transship'
model_dir:  #"C:/Users/Jerry/Desktop/thesis/code/MADRL/MADRL_main/results/TransshipNewEnv/InventoryManagement/happo/continue_transship/run_seed_1/models_4399"
training_bf: True

std_y_coef: [10.0,5.0]
std_x_coef: 1.0
use_linear_lr_decay: False
lr: 5e-4
critic_lr: 5e-4
hidden_size: 64
n_rollout_threads: 100
num_env_steps: 300000000
num_agents: 3
num_mini_batch: 1

use_clipped_value_loss: True
clip_param: 0.2

eval_interval: 20
n_no_improvement_thres: 20

# all_args.std_y_coef=[j/2. for j in all_args.std_y_coef]
# all_args.lr=all_args.lr/2
# all_args.critic_lr=all_args.critic_lr/2
# all_args.model_dir = str(config['run_dir'] / 'models')
# all_args.clip_bound=[(1-all_args.clip_param)**1.5,(1+all_args.clip_param)**1.5]

