# 就是把所有agent的意向transship和实际transship都作为state输入进去
algorithm_name: 'heuristic2' #'happo' #'heuristic2'  #'happo_continue'
experiment_name: 'heuristic'
model_dir:  #"C:/Users/Jerry/Desktop/thesis/code/MADRL/MADRL_main/results/TransshipNewEnv/InventoryManagement/happo/continue_transship_all_transship_obs/run_seed_1/models"
training_bf: False

std_y_coef: [0.5, 0.5]
std_x_coef: 1.0
use_linear_lr_decay: False
lr: 1e-5
critic_lr: 1e-3
hidden_size: 64
n_rollout_threads: 100
num_env_steps: 300000000
num_agents: 3
num_mini_batch: 1

use_valuenorm: False
use_proper_time_limits: False
use_clipped_value_loss: True
clip_param: 0.3

eval_interval: 20
n_no_improvement_thres: 10

# all_args.std_y_coef=[j/2. for j in all_args.std_y_coef]
# all_args.lr=all_args.lr/2
# all_args.critic_lr=all_args.critic_lr/2
# all_args.model_dir = str(config['run_dir'] / 'models')
# all_args.clip_bound=[(1-all_args.clip_param)**1.5,(1+all_args.clip_param)**1.5]

